language: node_js
node_js:
- 6.6.0
env:
  global:
    secure: Q3tsGPFtObdlLwWz59dE832CX28HB+2qtJmDmUlobzFC9Z56Bbgeu8AaGmM3oGbp2xh7lCcn1gMS7YP84csqImZnzgyNxP8iI8PuUwCjf8Rt4/WOTGTFbIU/r3bffb5Z4K8uJZwM7krsVFk96Ls9uSSa01cQxZIVNZGkQ7fGZJrulkA3Td8bsPPO/AuKP8dALHnNKPnD28PmKSA2YuhmyQEGp53/t5CveBBfSPpSqRXF3NCaZvj5WYioBQYMMtyg1X7XIN24FhlLL1v2aBfsZyWz9vNuEi+pD5HmQzqQTOot9I4TX5kvlT0lfk5V7HPLEfRy4iGFRWHirLLTGXizTifJ3pmMxnJKUB/ICBw5HZxxKXzyTAMuAqttjWHPBusGKMfaNdMNzIbaH6KbpKKGwcPqCXqSxe3fDXP0B6RYOjAmNdr3oqNJXisoRXFmvIjJtaX7LrtkRvQcd253UVJciiquwN11ZhqH7ulDu2Xwd9PMClqn6YJ1vJdUOTc4UWTo1dz68YhyZwAP62CgO0jT4CiH30iZlmoOZjjfIPbwGyZrCB+g5ildORMoyLa3J4uZQE44Ye/pjYQwnJE33blGHDyz0z4C66Sb126+bUIvQYj4/5XWpoOa6fC9Ph9vSVSZR16GAj+3EsPxEvj0ZPCYv3GhuT0sl13aOzBkKnggt/4=
