sudo: required
language: node_js
node_js:
- 6.6.0
env:
  global:
  - DB_USERNAME=dumbledore
  - NODE_ENV=production
  - secure: I+fOm2r0KTtWCq4nVjHIMEtMLqrbjAJJlBGom5md15opizEhkerbuS8gCOHVQNkcc7PgFEon06RFnFtEyvNGTkVDlTMyb+ue6FRhEbrY/heaNCWZY5MpK+wUSUAUyfbowmswzr9z9VdSCim5ZUnfxznyE6dkCN9mDIq0sd2YVciWBle/f/LqdYEpsIKFU98cvtxrNhRuihi1YqQoxYhKEVTrm42ucH4E2OZtpuh4kucTJ1D1IP82U93QJJ08FaMmAqOOoOs+X0ahOA/rXgMxEoB5dy4slYEQIJ7L6LNo1Ae8ocL/Budk6Z70RSXVPvol61E+cOdXdngt4WRp+rKRB/OCL4uT6HmuD/HIdtXHNiCRDoCwsfa7I7S2YoX2mFIkZyPxaSN4YvvGkDeJtKWGd5mqKK+w9qtGBIq5HUiPFWpmSMCtXZR1sI/bOxnl2PlVM/UM/+k7+wBff0cES1Fr0x0B8CfzWbZzezJEJcmHev5FfRgfQgt42cSXLxNIaLRN1BkloSxEQNdT4P19vr3o+AgAx2+uO056dZegfz9h1BOQ1RnqYh46L9xx1HCUsSJ3ancWl5+i33NEIpTzi2pQ1kIZZnN3htvKxu7KHoXTCqEWw8sXn8tODdxLA3tPggmD/Fls7vCB6RE0GcXDI6MsaZY8Yu8ufy0H1lLbAjEWv8U=

